name: voice_craft
description: A new Flutter project for Voice from silent vedio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  image_picker: ^1.0.6
  # firebase_ml_custom: ^0.2.0+3
  firebase_ml_model_downloader: ^0.2.4+8
  path_provider: ^2.1.2
  firebase_storage: ^11.6.0
  tflite_flutter: ^0.10.4
  file_picker: ^6.1.1
  better_audio_picker_plugin: ^0.0.6
  permission_handler: ^11.0.1
  camera: ^0.10.5+9
  record: ^5.0.4
  tflite_audio: ^0.3.0
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  get: ^4.6.6
  lottie: ^3.1.1
  smooth_page_indicator: ^1.1.0
  video_player: ^2.8.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - asets/emotion/
    - asets/Sound_identification/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SEASRN
      fonts:
        - asset: fonts/SEASRN.ttf
    - family: leaugespartan
      fonts:
        - asset: fonts/LeagueSpartan.otf
    - family: grandhotel
      fonts:
        - asset: fonts/GrandHotel.otf
    - family: debrosee
      fonts:
        - asset: fonts/Debrosee.ttf
    - family: kaushan
      fonts:
        - asset: fonts/Kaushan.otf
    - family: glorious
      fonts:
        - asset: fonts/Glorious.ttf
    - family: believeit
      fonts:
        - asset: fonts/BelieveIt.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
